# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/autumn/Repos/tateti

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/autumn/Repos/tateti

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/autumn/Repos/tateti/CMakeFiles /home/autumn/Repos/tateti/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/autumn/Repos/tateti/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tateti

# Build rule for target.
tateti: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tateti
.PHONY : tateti

# fast build rule for target.
tateti/fast:
	$(MAKE) -f CMakeFiles/tateti.dir/build.make CMakeFiles/tateti.dir/build
.PHONY : tateti/fast

GUI/gui.o: GUI/gui.cpp.o
.PHONY : GUI/gui.o

# target to build an object file
GUI/gui.cpp.o:
	$(MAKE) -f CMakeFiles/tateti.dir/build.make CMakeFiles/tateti.dir/GUI/gui.cpp.o
.PHONY : GUI/gui.cpp.o

GUI/gui.i: GUI/gui.cpp.i
.PHONY : GUI/gui.i

# target to preprocess a source file
GUI/gui.cpp.i:
	$(MAKE) -f CMakeFiles/tateti.dir/build.make CMakeFiles/tateti.dir/GUI/gui.cpp.i
.PHONY : GUI/gui.cpp.i

GUI/gui.s: GUI/gui.cpp.s
.PHONY : GUI/gui.s

# target to generate assembly for a file
GUI/gui.cpp.s:
	$(MAKE) -f CMakeFiles/tateti.dir/build.make CMakeFiles/tateti.dir/GUI/gui.cpp.s
.PHONY : GUI/gui.cpp.s

Tateti/tateti.o: Tateti/tateti.cpp.o
.PHONY : Tateti/tateti.o

# target to build an object file
Tateti/tateti.cpp.o:
	$(MAKE) -f CMakeFiles/tateti.dir/build.make CMakeFiles/tateti.dir/Tateti/tateti.cpp.o
.PHONY : Tateti/tateti.cpp.o

Tateti/tateti.i: Tateti/tateti.cpp.i
.PHONY : Tateti/tateti.i

# target to preprocess a source file
Tateti/tateti.cpp.i:
	$(MAKE) -f CMakeFiles/tateti.dir/build.make CMakeFiles/tateti.dir/Tateti/tateti.cpp.i
.PHONY : Tateti/tateti.cpp.i

Tateti/tateti.s: Tateti/tateti.cpp.s
.PHONY : Tateti/tateti.s

# target to generate assembly for a file
Tateti/tateti.cpp.s:
	$(MAKE) -f CMakeFiles/tateti.dir/build.make CMakeFiles/tateti.dir/Tateti/tateti.cpp.s
.PHONY : Tateti/tateti.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/tateti.dir/build.make CMakeFiles/tateti.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/tateti.dir/build.make CMakeFiles/tateti.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/tateti.dir/build.make CMakeFiles/tateti.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tateti"
	@echo "... GUI/gui.o"
	@echo "... GUI/gui.i"
	@echo "... GUI/gui.s"
	@echo "... Tateti/tateti.o"
	@echo "... Tateti/tateti.i"
	@echo "... Tateti/tateti.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

